development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: hda_development
  host: localhost
  socket: /tmp/mysqld.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

system:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: hda_development
  host: localhost
  socket: /tmp/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: hda_production
  host: localhost
  socket: /tmp/mysqld.sock
